---
sudo: required
dist: trusty
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - docker
env:
  - DJANGO_DATABASE_URL=postgresql://chaospizza:chaospizza@db:5432/chaospizza
install:
  - pip install coveralls
  - which coveralls >/dev/null 2>&1
  - make build-image
  - make check
before_script:
  - mkdir -p build/{db,coverage}
  - docker-compose up -d db
script:
  - make lint
  - make TESTOPTS="--verbose" test
after_success:
  - cp build/coverage/datafile .coverage
  - coveralls
after_script:
  - docker-compose down
