---
sudo: false
dist: trusty
language: python
cache: pip
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  # use pytest with the --reuse-db option and use the database already created by travis
  - DJANGO_DATABASE_URL=postgresql://postgres@localhost:5432/chaospizza
before_install:
  - psql -c 'create database test_chaospizza;' -U postgres
install:
  - make install-dev
  - make check
before_script:
  - make lint
  - python manage.py collectstatic --settings config.settings.test
script:
  - pytest --pythonwarnings=all --reuse-db --verbose --cov chaospizza --cov-report term-missing
after_success:
  - coveralls
