---
sudo: false
dist: trusty
language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
# use pytest with the --reuse-db option and use the database already created by travis
- DJANGO_DATABASE_URL=postgresql://postgres@localhost:5432/chaospizza
install: make install
before_script:
  - psql -c 'create database test_chaospizza;' -U postgres
script:
  - make lint
  - pytest --pythonwarnings=all --reuse-db
