---
sudo: false
dist: trusty
language: python
cache: pip
python:
  - "3.6"
services:
  - postgresql
  - docker
addons:
  postgresql: "9.6"
env:
  - DJANGO_DATABASE_URL=postgresql://postgres@localhost:5432/chaospizza
install:
  - make build-image
  - make check
before_script:
  - psql -c 'create database test_chaospizza;' -U postgres
  - mkdir -p build/coverage
  - make lint
script:
  - make TESTOPTS="--reuse-db --verbose" test
after_script:
  - cp build/coverage/datafile .coverage
after_success:
  - coveralls
