FROM python:3.6-alpine
ENV PYTHONUNBUFFERED 1
RUN apk update && apk add build-base libffi-dev postgresql-dev
RUN pip install --no-cache-dir pipenv

RUN mkdir -p /opt/app
WORKDIR /opt/app
COPY Pipfile ./
COPY Pipfile.lock ./
RUN pipenv install --system --deploy --dev
COPY src /opt/app

ENV DJANGO_STATIC_ROOT='/tmp/staticfiles' \
    DJANGO_STATIC_URL='/static/'
