FROM python:3.6-alpine
ENV PYTHONUNBUFFERED 1
RUN apk update && apk add build-base python-dev libffi-dev postgresql-dev

RUN mkdir -p /opt/app
COPY requirements/dev.txt /opt/app/requirements.txt
RUN cd /opt/app && pip install --no-cache-dir -r /opt/app/requirements.txt
COPY src /opt/app

ENV DJANGO_STATIC_ROOT='/tmp/staticfiles' \
    DJANGO_STATIC_URL='/static/'

WORKDIR /opt/app
