# Generated by Django 2.2 on 2019-07-13 07:13

from django.db import migrations


class Migration(migrations.Migration):  # noqa

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
